### ISSUE TITLE
UnicodeDecodeError Exception reading Test B errors.csv

### ISSUE THREAD

**Issue by Alastairm** [lilfolr/CITS4406-Assignment2#23]
'utf-8' codec can't decode byte 0xa5 in position 2882: invalid start byte
Unicode error hint: E+03,�,Jun-

The character � that it fails on is actually  ¥

**Comment by Alastairm** [comment]
~~(same in Test B.csv, it also has a ¥)~~

**Comment by JJHedges** [comment]
Was this run on the site? I tried to replicated it but couldn't get it, seems the advice online is that the default character set needs to be changed?

**Comment by Alastairm** [comment]
I get it when running the analyser by itself as well. Only on Test B Errors though.

**Comment by Alastairm** [comment]
data = Data("/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/csv_files/Test B errors.csv")

Delimiter Warning: could not determine delimiter, consider specifying using template. Continuing using comma
Traceback (most recent call last):
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/data.py", line 562, in read
    for line in f:
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 2882: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/data.py", line 541, in **init**
    self.read(self.filename)
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/data.py", line 584, in read
    for row in f:
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 2882: invalid start byte

**Comment by JJHedges** [comment]
I think i've fixed this error, we now open the csv file with a different text encoding format (ISO something or other)
