### ISSUE TITLE
Cannot alter the masked element exception

### ISSUE THREAD

**Issue by Alastairm** [lilfolr/CITS4406-Assignment2#32]
Melinda's ExcavatorWOdata1.csv, exception occurs during step [5/7] analysis (normaltest to be precise)

**Comment by Alastairm** [comment]
Traceback:

[Step 5/7] Running Analysis
Traceback (most recent call last):
  File "application.py", line 127, in <module>
    main(name)
  File "application.py", line 46, in main
    data.analysis()
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/data.py", line 806, in analysis
    column.analysis = self.analysers[column.type](column.values, self.std_devs_val)  
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/analyser.py", line 234, in **init**
    self.pval = mstats.normaltest(array(values))[1]
  File "/home/alastair/.local/lib/python3.4/site-packages/scipy/stats/mstats_basic.py", line 1699, in normaltest
    k, _ = kurtosistest(a, axis)
  File "/home/alastair/.local/lib/python3.4/site-packages/scipy/stats/mstats_basic.py", line 1683, in kurtosistest
    denom[denom < 0] = masked
  File "/home/alastair/.local/lib/python3.4/site-packages/numpy/ma/core.py", line 3086, in **setitem**
    raise MaskError('Cannot alter the masked element.')
numpy.ma.core.MaskError: Cannot alter the masked element.

**Comment by Alastairm** [comment]
[Step 5/7] Running Analysis
Traceback (most recent call last):
  File "application.py", line 127, in <module>
    main(name)
  File "application.py", line 46, in main
    data.analysis()
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/data.py", line 806, in analysis
    column.analysis = self.analysers[column.type](column.values, self.std_devs_val)  
  File "/home/alastair/Documents/CITS3200/django_env/mysite/common/analyser/analyser.py", line 234, in __init__
    self.pval = mstats.normaltest(array(values))[1]
  File "/home/alastair/.local/lib/python3.4/site-packages/scipy/stats/mstats_basic.py", line 1699, in normaltest
    k, _ = kurtosistest(a, axis)
  File "/home/alastair/.local/lib/python3.4/site-packages/scipy/stats/mstats_basic.py", line 1683, in kurtosistest
    denom[denom < 0] = masked
  File "/home/alastair/.local/lib/python3.4/site-packages/numpy/ma/core.py", line 3086, in __setitem__
    raise MaskError('Cannot alter the masked element.')
numpy.ma.core.MaskError: Cannot alter the masked element.

**Comment by Alastairm** [comment]
can't reproduce on other systems...
